#!/bin/bash

if [[ $# != 2 ]]; then
	echo "USAGE: $0 <path> <filename>" >&2
	exit 1
fi

HandBrakeCLI -i "$1" -o "$2" --main-feature --large-file -q 25 -E copy -e x264 -s 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20 -m
