#!/bin/sh

if [ -z "$1" ]
then
	echo "Must provide a filename!"
	exit
fi

#HandBrakeCLI -L -f mkv --deinterlace="slower" -p  -e x264 -b 2000 -2  -T  -a 1 -E ac3 -B 160 -R 0 -6 dpl2 -D 1 -m -x ref=2:bframes=2:me=umh -i /dev/dvd -o "$1" $2 $3
HandBrakeCLI -L -f mkv -p  -e x264 -b 2000 -2  -T  -a 1 -E ac3 -B 160 -R 0 -6 dpl2 -D 1 -m -x ref=2:bframes=2:me=umh -i /dev/dvd -o "$1" $2 $3
